syncInterval: 30s
statePath: "/data/sync-state.db"
caddy:
  adminUrl: "http://caddy:2019"
dns:
  provider: "cloudflare"
  zones: ["eslack.net"]
  token: "" # Prefer CLOUDFLARE_API_TOKEN environment variable
  ttl: 300
reconcile:
  dryRun: false  # Don't create DNS records if true
  owner: "eslack"
  protectedRecords:
    - "example.eslack.com"
