services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"  # Admin API port
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sync-network
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]

  caddy-dns-sync:
    build: ../.
    container_name: caddy-dns-sync
    ports:
      - "8080:8080"
    environment:
      - CADDY_ADMIN_URL=http://caddy:2019
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-dummy-token}
    volumes:
      - ./config.yaml:/app/config.yaml
      - caddy_dns_sync_state:/data
    networks:
      - sync-network
    depends_on:
      - caddy

volumes:
  caddy_data:
  caddy_config:
  caddy_dns_sync_state:

networks:
  sync-network:
